---
- hosts: master_hosts
  vars:
          masterconf: ""
  tasks:
          - name: non root user conf step 2
            shell: mkdir -p $HOME/.kube/ config
            become: yes

          - name: non root user conf step 3
            command: "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
            become: yes

          - name: non root user conf step 4
            shell: sudo chown $(id .u):$(id -g) $HOME/.kube/config
            become: yes

          - name: Initialice pod network
            shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
            become: yes

          - name: Add nodes information
            debug: var=masterconf
