---
- hosts: master_hosts
  vars:
          masterconf: ""
  tasks:
          - name: Start Kubernetes Cluster
            shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=10.0.0.153 --ignore-preflight-errors=all
            register: masterconf
            become: yes

          - name: non root user conf step 1
            shell: mkdir -p $HOME/ .kube
            become: yes

          - name: non root user conf step 2
            shell: mkdir -p $HOME/.kube/ config
            become: yes

          - name: non root user conf step 3
            command: "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
            become: yes

          - name: non root user conf step 4
            shell: chown $(id .u):$(id -g) $HOME/.kube/config
            become: yes

          - name: Initialice pod network
            shell: kubectl apply -f kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
            become: yes

          - name: Add nodes information
            debug: var=masterconf
