---
- hosts: master_hosts
  vars:
          localipadres: ""
  tasks:
          - name: Get Local IP Adress
            shell: "/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'"
            register: localipadres
            become: yes

          - name: Current Config IP Adress
            debug: var=localipadres