---
- hosts: cluster_hosts
  vars:
          package1: ""
  tasks:
          - name: get update
            apt: update_cache=true
            become: true

          - name: Install https transport
            apt: pkg=apt-transport-https state=installed update_cache=true
            become: true

          - name: Install CURL
            apt: pkg=curl state=installed update_cache=true
            become: true

          - name: Add kubernetes key
            shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

          - name: add new kube repo
            shell: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" >> /etc/apt/sources.list.d/kubernetes.list
            become: true

          - name: get update
            apt: update_cache=true
            become: true

          - name: Install docker
            apt: pkg=kubelet state=installed update_cache=true
            become: true

          - name: Install docker
            apt: pkg=kubeadm state=installed update_cache=true
            become: true

          - name: Install docker
            apt: pkg=kubectl state=installed update_cache=true
            become: true

          - name: markdown
            shell: apt-mark hold kubelet kubeadm kubectl
            become: true